### PR TITLE
Include a "standard" link to the list of discussions

### PR DESCRIPTION
**Pull request by mjang**
I've done some hard coding. (I couldn't figure out how to set this up "properly." But since this applies to all pages, I'm not sure if that matters.)

I don't claim to know any/all PR requirements -- I'm using this as a learning experience.

Ref #150 and https://github.com/nginx/unit/pull/1299

Here's how it looks in the local build.
Screenshot 2024-06-03 at 2 02 05 PM

### CODE REVIEW

**Comment by callahad** [comment]
Somehow missed this in my review queue. Would love to replace the icon with either a [GitHub logo](https://fontawesome.com/icons/github?f=brands&s=solid) or [chat bubbles](https://fontawesome.com/icons/comments?f=classic&s=solid) from Font Awesome and tweak the text to be more along the lines of "Discuss on GitHub" or similar.

**Comment by lcrilly** [comment]
@callahad, would an emoji suffice? 💬

**Comment by callahad** [comment]
Pushed a patch so this now renders as:

> Screenshot 2024-06-23 at 11 58 26

**Review by avahahn — APPROVED** [review]
LGTM

**Pull request merged**
